######################################################################
# Automatically generated by qmake (2.01a) dom oct 28 11:35:54 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bounce_bird.h bounce_window.h bouncing_area.h
SOURCES += bounce_bird.cc bounce_window.cc bouncing_area.cc main.cc
